from .models import User
from .models import CartItem
from .models import Category
from .models import Comment
from .models import Discount
from .models import Inventory
from .models import Like
from .models import OrderDetails
from .models import OrderItems
from models import PaymentDetails
from models import ProductImage
from models import Product
from models import Rating
from models import ShoppingSession
from models import UserInfo
from models import UserPayment
